"""IIIF Presentation API 2.0 document builders."""

from __future__ import annotations

from ..config import GenerationConfig
from ..models import DirectoryInfo, GeneratedDocument, ImageInfo
from .base import (
    COLLECTION_FILENAME,
    MANIFEST_FILENAME,
    child_document,
    collection_id,
    manifest_id,
)

CONTEXT = "http://iiif.io/api/presentation/2/context.json"
TYPE_NAMES = {"manifest": "sc:Manifest", "collection": "sc:Collection"}
IMAGE_SERVICE_PROFILE = "http://iiif.io/api/image/2/level0.json"


def _metadata(label: str) -> list[dict[str, str]]:
    return [
        {
            "label": "Description",
            "value": (
                f"IIIF Presentation 2.0 manifest generated by "
                f"iiif-manifest-generator for {label}"
            ),
        }
    ]


def _canvas(
    config: GenerationConfig, dir_info: DirectoryInfo, info: ImageInfo, index: int
) -> dict:
    canvas_id = f"{manifest_id(config, dir_info)}/canvas/{index}"
    return {
        "@id": canvas_id,
        "@type": "sc:Canvas",
        "label": info.rel_path.name,
        "width": info.width,
        "height": info.height,
        "images": [
            {
                "@type": "oa:Annotation",
                "motivation": "sc:painting",
                "resource": {
                    "@id": info.iip.full_url,
                    "@type": "dctypes:Image",
                    "format": info.mime,
                    "width": info.width,
                    "height": info.height,
                    "service": {
                        "@id": info.iip.info_url,
                        "@type": "ImageService2",
                        "profile": IMAGE_SERVICE_PROFILE,
                    },
                    "on": canvas_id,
                },
                # NOTE (deviation from plan): the official validator (iiif_prezi)
                # requires 'on' on the oa:Annotation itself; the plan only put it
                # inside 'resource'. Both are kept so the plan's Step 17 unit
                # test (resource['on']) and the official validator both pass.
                "on": canvas_id,
            }
        ],
    }


def build_manifest(config: GenerationConfig, dir_info: DirectoryInfo) -> GeneratedDocument:
    doc_id = manifest_id(config, dir_info)
    doc: dict = {
        "@context": CONTEXT,
        "@id": doc_id,
        "@type": "sc:Manifest",
        "label": dir_info.label,
        "metadata": _metadata(dir_info.label),
        "sequences": [
            {
                "@id": f"{doc_id}/sequence/normal",
                "@type": "sc:Sequence",
                "canvases": [
                    _canvas(config, dir_info, info, i)
                    for i, info in enumerate(dir_info.images, start=1)
                ],
            }
        ],
    }
    if config.attribution:
        doc["attribution"] = config.attribution
    if config.license:
        doc["license"] = config.license
    if config.thumbnails and dir_info.images and dir_info.images[0].iip.thumbnail_url:
        first = dir_info.images[0]
        doc["thumbnail"] = {"@id": first.iip.thumbnail_url, "format": first.mime}
    return GeneratedDocument(
        dir_info=dir_info, kind="manifest", data=doc, filename=MANIFEST_FILENAME
    )


def build_collection(
    config: GenerationConfig, dir_info: DirectoryInfo
) -> GeneratedDocument:
    doc_id = collection_id(config, dir_info)
    members: list[dict] = []
    if dir_info.has_manifest:
        members.append(
            {
                "@id": manifest_id(config, dir_info),
                "@type": "sc:Manifest",
                "label": dir_info.label,
            }
        )
    for child in dir_info.documentable_children:
        child_id, kind = child_document(config, child)
        members.append(
            {"@id": child_id, "@type": TYPE_NAMES[kind], "label": child.label}
        )
    doc = {
        "@context": CONTEXT,
        "@id": doc_id,
        "@type": "sc:Collection",
        "label": dir_info.label,
        "metadata": _metadata(dir_info.label),
        "members": members,
    }
    return GeneratedDocument(
        dir_info=dir_info, kind="collection", data=doc, filename=COLLECTION_FILENAME
    )
