"""IIIF Presentation API 2.1 document builders."""

# NOTE (deviation from plan, required by the official validator):
# The official validator validates 2.x documents with iiif_prezi's
# ManifestReader, which (a) only recognizes the 2.0 context URI for BOTH
# 2.0 and 2.1 (ManifestReader.contexts maps '2.1' ->
# 'http://iiif.io/api/presentation/2/context.json'; the 2.1 context string
# is rejected as "Top level @context is not known"), and (b) requires the
# '@id'/'@type' key style for every resource ("Every resource must have
# @type"). A document using id/type keys or the 2.1 context string fails
# official validation. This builder therefore emits 2.0-style syntax and
# keeps the 2.1 Image API profile, which is the one 2.1-specific element
# the official validator does check for.
from __future__ import annotations

from ..config import GenerationConfig
from ..models import DirectoryInfo, GeneratedDocument, ImageInfo
from .base import (
    COLLECTION_FILENAME,
    MANIFEST_FILENAME,
    child_document,
    collection_id,
    manifest_id,
)

CONTEXT = "http://iiif.io/api/presentation/2/context.json"
TYPE_NAMES = {"manifest": "sc:Manifest", "collection": "sc:Collection"}
IMAGE_SERVICE_PROFILE = "http://iiif.io/api/image/2.1/level0.json"


def _metadata(label: str) -> list[dict[str, str]]:
    return [
        {
            "label": "Description",
            "value": (
                f"IIIF Presentation 2.1 manifest generated by "
                f"iiif-manifest-generator for {label}"
            ),
        }
    ]


def _canvas(
    config: GenerationConfig, dir_info: DirectoryInfo, info: ImageInfo, index: int
) -> dict:
    canvas_id = f"{manifest_id(config, dir_info)}/canvas/{index}"
    return {
        "@id": canvas_id,
        "@type": "sc:Canvas",
        "label": info.rel_path.name,
        "width": info.width,
        "height": info.height,
        "images": [
            {
                "@type": "oa:Annotation",
                "motivation": "sc:painting",
                "resource": {
                    "@id": info.iip.full_url,
                    "@type": "dctypes:Image",
                    "format": info.mime,
                    "width": info.width,
                    "height": info.height,
                    "service": {
                        "@id": info.iip.info_url,
                        "@type": "ImageService2",
                        "profile": IMAGE_SERVICE_PROFILE,
                    },
                    "on": canvas_id,
                },
                "on": canvas_id,
            }
        ],
    }


def build_manifest(config: GenerationConfig, dir_info: DirectoryInfo) -> GeneratedDocument:
    doc_id = manifest_id(config, dir_info)
    doc: dict = {
        "@context": CONTEXT,
        "@id": doc_id,
        "@type": "sc:Manifest",
        "label": dir_info.label,
        "metadata": _metadata(dir_info.label),
        "sequences": [
            {
                "@id": f"{doc_id}/sequence/normal",
                "@type": "sc:Sequence",
                "canvases": [
                    _canvas(config, dir_info, info, i)
                    for i, info in enumerate(dir_info.images, start=1)
                ],
            }
        ],
    }
    if config.attribution:
        doc["attribution"] = config.attribution
    if config.license:
        doc["license"] = config.license
    if config.thumbnails and dir_info.images and dir_info.images[0].iip.thumbnail_url:
        first = dir_info.images[0]
        doc["thumbnail"] = {"@id": first.iip.thumbnail_url, "format": first.mime}
    return GeneratedDocument(
        dir_info=dir_info, kind="manifest", data=doc, filename=MANIFEST_FILENAME
    )


def build_collection(
    config: GenerationConfig, dir_info: DirectoryInfo
) -> GeneratedDocument:
    doc_id = collection_id(config, dir_info)
    members: list[dict] = []
    if dir_info.has_manifest:
        members.append(
            {
                "@id": manifest_id(config, dir_info),
                "@type": "sc:Manifest",
                "label": dir_info.label,
            }
        )
    for child in dir_info.documentable_children:
        child_id, kind = child_document(config, child)
        members.append(
            {"@id": child_id, "@type": TYPE_NAMES[kind], "label": child.label}
        )
    doc = {
        "@context": CONTEXT,
        "@id": doc_id,
        "@type": "sc:Collection",
        "label": dir_info.label,
        "metadata": _metadata(dir_info.label),
        "members": members,
    }
    return GeneratedDocument(
        dir_info=dir_info, kind="collection", data=doc, filename=COLLECTION_FILENAME
    )

