"""IIIF Presentation API 3.0 document builders."""

from __future__ import annotations

from ..config import GenerationConfig
from ..models import DirectoryInfo, GeneratedDocument, ImageInfo
from .base import (
    COLLECTION_FILENAME,
    MANIFEST_FILENAME,
    child_document,
    collection_id,
    manifest_id,
)

# NOTE (deviation from plan): the official validator's 3.0 schema (iiif_3_0.json)
# requires the http (not https) context const:
#   {"oneOf": [array-of-http(s)-uris, {"const": "http://iiif.io/api/presentation/3/context.json"}]}
CONTEXT = "http://iiif.io/api/presentation/3/context.json"
TYPE_NAMES = {"manifest": "Manifest", "collection": "Collection"}
IMAGE_PROTOCOL = "http://iiif.io/api/image/3/1/context.json"
IMAGE_API_2_PROFILE = "http://iiif.io/api/image/2/level0.json"


def _label(text: str) -> dict:
    return {"none": [text]}


def _metadata(doc_id: str) -> list[dict]:
    return [
        {
            "id": f"{doc_id}/metadata/generated-by",
            "label": {"none": ["Generated by"]},
            "value": {"none": ["iiif-manifest-generator"]},
        }
    ]


def _image_service(info: ImageInfo, image_api_version: str) -> dict:
    if image_api_version == "3":
        return {
            "id": info.iip.info_url,
            "type": "ImageService3",
            "format": info.mime,
            "width": info.width,
            "height": info.height,
            "protocol": IMAGE_PROTOCOL,
            "profile": "level2",
            "maxWidth": info.width,
            "maxHeight": info.height,
        }
    return {
        "id": info.iip.info_url,
        "type": "ImageService2",
        "profile": IMAGE_API_2_PROFILE,
    }


def _canvas(
    config: GenerationConfig, dir_info: DirectoryInfo, info: ImageInfo, index: int
) -> dict:
    canvas_id = f"{manifest_id(config, dir_info)}/canvas/{index}"
    return {
        "id": canvas_id,
        "type": "Canvas",
        "label": _label(info.rel_path.name),
        "width": info.width,
        "height": info.height,
        "items": [
            {
                "id": f"{canvas_id}/page/1",
                "type": "AnnotationPage",
                "items": [
                    {
                        "id": f"{canvas_id}/page/1/annotation/1",
                        "type": "Annotation",
                        "motivation": "painting",
                        "body": _image_service(info, config.image_api_version),
                        "target": canvas_id,
                    }
                ],
            }
        ],
    }


def build_manifest(config: GenerationConfig, dir_info: DirectoryInfo) -> GeneratedDocument:
    doc_id = manifest_id(config, dir_info)
    doc: dict = {
        "@context": CONTEXT,
        "id": doc_id,
        "type": "Manifest",
        "label": _label(dir_info.label),
        "metadata": _metadata(doc_id),
        "items": [
            _canvas(config, dir_info, info, i)
            for i, info in enumerate(dir_info.images, start=1)
        ],
    }
    # 3.0 removed license/attribution: use rights + requiredStatement instead.
    if config.attribution:
        doc["requiredStatement"] = {
            "label": _label("Attribution"),
            "value": _label(config.attribution),
        }
    if config.license:
        doc["rights"] = config.license
    # 3.0 thumbnails are an array.
    if config.thumbnails and dir_info.images and dir_info.images[0].iip.thumbnail_url:
        first = dir_info.images[0]
        doc["thumbnail"] = [
            {"id": first.iip.thumbnail_url, "type": "Image", "format": first.mime}
        ]
    return GeneratedDocument(
        dir_info=dir_info, kind="manifest", data=doc, filename=MANIFEST_FILENAME
    )


def build_collection(
    config: GenerationConfig, dir_info: DirectoryInfo
) -> GeneratedDocument:
    doc_id = collection_id(config, dir_info)
    items: list[dict] = []
    if dir_info.has_manifest:
        items.append(
            {
                "id": manifest_id(config, dir_info),
                "type": "Manifest",
                "label": _label(dir_info.label),
            }
        )
    for child in dir_info.documentable_children:
        child_id, kind = child_document(config, child)
        items.append(
            {"id": child_id, "type": TYPE_NAMES[kind], "label": _label(child.label)}
        )
    doc = {
        "@context": CONTEXT,
        "id": doc_id,
        "type": "Collection",
        "label": _label(dir_info.label),
        "metadata": _metadata(doc_id),
        "items": items,
    }
    return GeneratedDocument(
        dir_info=dir_info, kind="collection", data=doc, filename=COLLECTION_FILENAME
    )
