"""IIIF Presentation API 4.0 document builders."""

from __future__ import annotations

from ..config import GenerationConfig
from ..models import DirectoryInfo, GeneratedDocument, ImageInfo
from .base import (
    COLLECTION_FILENAME,
    MANIFEST_FILENAME,
    child_document,
    collection_id,
    manifest_id,
)

# NOTE (deviation from plan, required by the official validator): the
# validator's 4.0 schema requires the http (not https) context:
#   {"const": "http://iiif.io/api/presentation/4/context.json"}
CONTEXT = "http://iiif.io/api/presentation/4/context.json"
TYPE_NAMES = {"manifest": "Manifest", "collection": "Collection"}
IMAGE_PROTOCOL = "http://iiif.io/api/image/3/1/context.json"
IMAGE_API_2_PROFILE = "http://iiif.io/api/image/2/level0.json"


def _label(text: str) -> dict:
    # NOTE (deviation from plan): the official 4.0 schema defines label/value
    # as an lngString object ({"none": [...]}); plain strings are rejected
    # ("'x' is not of type 'object' ... must have a language and value must
    # be an array").
    return {"none": [text]}


def _metadata(doc_id: str) -> list[dict]:
    return [
        {
            "id": f"{doc_id}/metadata/generated-by",
            "label": _label("Generated by"),
            "value": _label("iiif-manifest-generator"),
        }
    ]


def _body(info: ImageInfo, image_api_version: str) -> dict:
    if image_api_version == "3":
        service = {
            "id": info.iip.info_url,
            "type": "ImageService3",
            "profile": "level2",
            "protocol": IMAGE_PROTOCOL,
        }
    else:
        # 4.0 documents may reference Image API 2 services using the
        # 2-style '@id'/'@type' service entry (accepted by the official
        # 4.0 schema's Service definition).
        service = {
            "@id": info.iip.info_url,
            "@type": "ImageService2",
            "profile": IMAGE_API_2_PROFILE,
        }
    return {
        "id": info.iip.full_url,
        "type": "Image",
        "format": info.mime,
        "service": [service],
    }


def _canvas(
    config: GenerationConfig, dir_info: DirectoryInfo, info: ImageInfo, index: int
) -> dict:
    canvas_id = f"{manifest_id(config, dir_info)}/canvas/{index}"
    return {
        "id": canvas_id,
        "type": "Canvas",
        "label": _label(info.rel_path.name),
        "width": info.width,
        "height": info.height,
        "items": [
            {
                "id": f"{canvas_id}/page/1",
                "type": "AnnotationPage",
                "items": [
                    {
                        "id": f"{canvas_id}/page/1/annotation/1",
                        "type": "Annotation",
                        "motivation": ["painting"],
                        "body": _body(info, config.image_api_version),
                        # NOTE (deviation from plan): the official 4.0 schema
                        # (Target.json) requires the annotation target to be a
                        # typed object, not a plain URI string; for painting
                        # that is a CanvasRef (id + type "Canvas"). The
                        # validator's unique-id check ignores 'target' values,
                        # so reusing the canvas id here is safe.
                        "target": {"id": canvas_id, "type": "Canvas"},
                    }
                ],
            }
        ],
    }


def build_manifest(config: GenerationConfig, dir_info: DirectoryInfo) -> GeneratedDocument:
    doc_id = manifest_id(config, dir_info)
    doc: dict = {
        "@context": CONTEXT,
        "id": doc_id,
        "type": "Manifest",
        "label": _label(dir_info.label),
        "metadata": _metadata(doc_id),
        "items": [
            _canvas(config, dir_info, info, i)
            for i, info in enumerate(dir_info.images, start=1)
        ],
    }
    if config.attribution:
        doc["requiredStatement"] = {
            "label": _label("Attribution"),
            "value": _label(config.attribution),
        }
    if config.license:
        doc["rights"] = config.license
    if config.thumbnails and dir_info.images and dir_info.images[0].iip.thumbnail_url:
        first = dir_info.images[0]
        doc["thumbnail"] = [
            {"id": first.iip.thumbnail_url, "type": "Image", "format": first.mime}
        ]
    return GeneratedDocument(
        dir_info=dir_info, kind="manifest", data=doc, filename=MANIFEST_FILENAME
    )


def build_collection(
    config: GenerationConfig, dir_info: DirectoryInfo
) -> GeneratedDocument:
    doc_id = collection_id(config, dir_info)
    items: list[dict] = []
    if dir_info.has_manifest:
        items.append(
            {
                "id": manifest_id(config, dir_info),
                "type": "Manifest",
                "label": _label(dir_info.label),
            }
        )
    for child in dir_info.documentable_children:
        child_id, kind = child_document(config, child)
        items.append(
            {"id": child_id, "type": TYPE_NAMES[kind], "label": _label(child.label)}
        )
    doc = {
        "@context": CONTEXT,
        "id": doc_id,
        "type": "Collection",
        "label": _label(dir_info.label),
        "metadata": _metadata(doc_id),
        "items": items,
    }
    return GeneratedDocument(
        dir_info=dir_info, kind="collection", data=doc, filename=COLLECTION_FILENAME
    )
